version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - web_network
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 3001:3001
    deploy:
      replicas: 3
      restart_policy: on-failure
    networks:
      - web_network
      
networks:
  web_network:
    driver: bridge
