version: '3'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - overlay
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 3001:3001
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - overlay

networks:
  overlay:
